[package]
authors = ["Fabio Pungg <fabiopungg@gmail.com>"]
edition = "2021"
name = "aoc2022-day14"
version = "0.1.0"

[dependencies]
anyhow = "1.0.68"
color-eyre = "0.6.2"
derive_more = "0.99.17"
itertools = "0.10.5"
nom = "7.1.1"

[dev-dependencies]
assert_ok = "1.0.2"
pretty_assertions = "1.3.0"
